# Generated by Django 4.0.1 on 2022-01-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_alumni_profile_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile'),
        ),
    ]
