# Generated by Django 4.0.1 on 2022-01-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_particular_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.profile'),
        ),
    ]
