# Generated by Django 4.0.1 on 2022-01-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_particular_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Particular',
        ),
    ]
