# Generated by Django 4.0.1 on 2022-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_1',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_2',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_3',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_4',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_5',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_6',
            name='particular',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
