# Generated by Django 4.0.1 on 2022-02-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_semester_1_particular_semester_2_particular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/student_images/'),
        ),
    ]
