# Generated by Django 4.0.1 on 2022-02-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.profile'),
        ),
    ]
