# Generated by Django 4.0.1 on 2022-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_semester_1_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semester_1',
            new_name='Semester',
        ),
        migrations.RemoveField(
            model_name='semester_3',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='semester_4',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='semester_5',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='semester_6',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Semester_2',
        ),
        migrations.DeleteModel(
            name='Semester_3',
        ),
        migrations.DeleteModel(
            name='Semester_4',
        ),
        migrations.DeleteModel(
            name='Semester_5',
        ),
        migrations.DeleteModel(
            name='Semester_6',
        ),
    ]
