# Generated by Django 4.0.1 on 2022-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_semester_1_semester_remove_semester_3_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
