# Generated by Django 4.0.1 on 2022-02-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('applying_for', models.CharField(choices=[('Health Science Courses', 'Health Science Courses'), ('Engineering Courses', 'Engineering Courses'), ('Management Courses', 'Management Courses'), ('Certified Courses', 'Certified Courses'), ('Other Courses', 'Other Courses')], max_length=50)),
                ('query', models.TextField()),
            ],
        ),
    ]
