# Generated by Django 4.0.1 on 2022-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('pre_requisite', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('breif_desc', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Health Science Courses', 'Health Science Courses'), ('Engineering Courses', 'Engineering Courses'), ('Management Courses', 'Management Courses'), ('Certified Courses', 'Certified Courses')], max_length=50)),
            ],
        ),
    ]
