# Generated by Django 3.2.10 on 2022-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_course_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='admitcard')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('paper', models.CharField(max_length=200)),
                ('exam_centre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('office_at', models.CharField(max_length=100)),
                ('period_of', models.CharField(max_length=100)),
                ('period_to', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='idcard')),
                ('fathers_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('issuing_year', models.CharField(max_length=100)),
                ('validity_year', models.CharField(max_length=100)),
            ],
        ),
    ]
