# Generated by Django 3.2.10 on 2022-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20220520_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='enrollment_no',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment_no',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='enrollment_no',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
