# Generated by Django 3.2.10 on 2022-05-20 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20220520_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='center_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
