# Generated by Django 3.2.10 on 2022-05-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_certificate_center_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitcard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='idcard',
            options={'ordering': ['-id']},
        ),
    ]
