# Generated by Django 3.2.10 on 2022-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20220608_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultHideUnHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
