# Generated by Django 3.2.10 on 2022-06-12 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_resulthideunhide'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='instruction',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
